Friendships v1
alejandrotoledoweb/ror-social-scaffold pull request #3
Opened 2020-12-08 22:39 UTC by alejandrotoledoweb

## Friendships v1

In this branch we added the model and controller for friendship between users.
Also, we create and modify the views to display the friendships and the pending friendships between users.

2020-12-09 04:06 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Alejandro Toledo Freire** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Add a screenshot in your README file
- [ ] Add spec tests to your project
- [x] In Friendship class, both sender and receiver should be associated with User class
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2020-12-09 21:02 UTC, blackpintz requested changes
# Status: Changes Required 🤓

### Hello team 😄,

**Great job implementing the requested changes 💪. However, there are still a few fixes needed.**

1). **You only wrote spec tests for two files in `app/models` directory. Add tests for all the other files as well.**

2). **Add tests for your `helpers` and ` views`.**

3). **You have `rubocop` error.**
![rubocop](https://user-images.githubusercontent.com/38922385/101686787-97ac3a80-3a7a-11eb-8485-098a95cf593a.png)

4). **Check more in the comments below.**

5).  **The screenshot images in your readme file are broken**.

### Happy coding 🥂 

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-09 21:02 UTC, ghost commented on app/models/user.rb
> +  has_many :inverse_friendships, class_name: :Friendship, foreign_key: :friend_id
Write spec tests for the above associations. Hint you can use [shoulda matchers](https://matchers.shoulda.io/) to write single line tests.

2020-12-09 21:02 UTC, ghost commented on app/models/user.rb
>  end
Write spec tests for the above methods. If you have any methods that you are not using outside the User class, you can declare them private and avoid writing tests for them.

2020-12-10 17:32 UTC, alejandrotoledoweb commented
I checked for rubocop issues in Actions section but I got nothing

2020-12-10 18:33 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @alejandrotoledoweb and @Blaise-Shyaka :clap: :clap:
#### You have done an incredible job writing such a comprehensive integration test. As much as I'm eager to approve this project some of the required changes from the last review were not implemented. Check my comments below :point_down:

#### Tests:
- **_Write tests for public methods in the User model as mentioned in the last review_**

- **_Write association tests for the User model(similar to the association test you wrote in the friendship spec) as mentioned in the last review_**

#### _Reviewed by Temitayo Adeleke_

2020-12-11 04:16 UTC, andresporras3423 requested changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Alejandro Toledo Freire** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the development branch
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

2020-12-21 14:55 UTC, merged