Friendship v2
alejandrotoledoweb/ror-social-scaffold pull request #4
Opened 2020-12-14 20:42 UTC by alejandrotoledoweb

## Friendship v2

In this branch I implement friendships with 2 rows for mutual friendship. Changing the associations and modifying the user methods used before.

2020-12-14 21:55 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've really done well implementing the milestone requirements. You also did well to add unit and integration test suites.
However, there are some changes required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] I could not test your implemented feature.
- Here's the error I'm having whenever I try to access your project:

![22-26-35](https://user-images.githubusercontent.com/26856491/102137706-89379780-3e5b-11eb-906a-fe52b4a85f1f.png)

- Although I do not understand why you're having the RSpec configuration in the `user_helper.rb` file of your `helpers` directory, Kindly check this file to fix this error.

**Having checked your codebase, here are some hints about implementing mutual friendship in the most efficient way.**

- [ ] When friendship is confirmed, you can create an additional row by adding this code snippet into your friendship model, like this:

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [ ] Thanks to the snippet above, you can find user friends only by user_id in the friendships table:
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

```

- [ ] Also, User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
 
```

- [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data, it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [ ] In order to get all posts written by user and their friends, you can use simple method in User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

**[ COMMENTS ]**
- Please note that the explanations above concerning implementing mutual friendship are to enable you to see an efficient implementation of mutual friendship.

- In my opinion, it does not mean that you should completely refactor yours to use the method stated above. However, you are advised to see how you can use it to improve your own version of the implementation.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-12-14 22:29 UTC, alejandrotoledoweb commented
In order to test the helper methods I read that recommends to put the configuration inside the `user_helper.rb`

2020-12-14 22:54 UTC, teekaytech commented
> In order to test the helper methods I read that recommends to put the configuration inside the `user_helper.rb`
> 

Okay. If that's the case, then you should find a way to make it work without affecting the project flow. All the best.

2020-12-15 15:24 UTC, alejandrotoledoweb commented
Now I can access the project with `rails server` but the test for feature are not working, if you have any advise please let me know

2020-12-15 15:26 UTC, alejandrotoledoweb commented
Also I put the configuration in the `rails_helper.rb` instead on the `user_helper.rb`

2020-12-15 18:55 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

The way you have used ActiveRecord methods is truly impressive especially the `friend_post` scope in post.rb. I have seen very few people handle ActiveRecords that well. Well done 👏 !

### However, we need to work on some changes before we can merge.

After rejecting a friendship, I can still see the "accept" and "reject" button beside the user on the "All Users" page and on the user profile page. You can use server logs to see what's happening. Please remove the buttons after the logged-in user has rejected friendship.

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-12-15 18:55 UTC, tirthajyoti-ghosh commented on app/models/user.rb
> +  end
These two methods can be converted to scopes. 

Right now, you are using Ruby methods to process pending friendships and friend requests. But if you have used ActiveRecord methods, the processing would have been a lot faster as the database was created to store and query data it is always more efficient than Ruby.

- [ ] Please convert these methods to scopes.

2020-12-15 18:55 UTC, tirthajyoti-ghosh commented on app/views/users/_pending.html.erb
> +  <% end %>
Please remove all logic from your views. Move them to helpers.

**IMPORTANT!** I am only pointing this out here. Please go through your views and refactor the code as necessary.

2020-12-15 19:53 UTC, alejandrotoledoweb commented
I tried to reject a friendship request and then the buttons for accept and reject disappear, please check this again.

2020-12-15 19:56 UTC, tirthajyoti-ghosh commented
Try again after creating 2 or 3 friendships. You will see the buttons still
remains.

On Wed, Dec 16, 2020, 1:23 AM Alejandro Toledo <notifications@github.com>
wrote:

> I tried to reject a friendship request and then the buttons for accept and
> reject disappear, please check this again.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/alejandrotoledoweb/ror-social-scaffold/pull/4#issuecomment-745528286>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANYNLDB4D55L7HOD4MAVFCDSU65ETANCNFSM4U3JZG5Q>
> .
>

2020-12-17 18:45 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

A great effort implementing the suggested changes 👍 
However, we still need to make some changes in order to get this project approved 💪 
Kindly check my comments below 👇  and resubmit your project once they are done ⏩ 
Good luck! 😃 
## Mandatory changes
- The project has a bug due to the associations and foreign keys you have implemented. Try to move your scopes into the users model, and double-check the foreign keys in your friendships models

2020-12-17 18:56 UTC, alejandrotoledoweb commented
Please can you explain to me more about the bug you are talking about

2020-12-17 20:21 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @alejandrotoledoweb :+1:
#### Good job so far. However, the database migration process outputted an error when I was trying to run `rails db:migrate`. Check the image and the comment below :point_down:

#### Migration Error:
- _The migration process output this error: "rails aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'confirmed' for Friendship."_
![Screenshot from 2020-12-17 14-14-36](https://user-images.githubusercontent.com/48312803/102539198-fd985380-4072-11eb-9dde-081ca2a6ee03.png)

#### _Review by Temitayo Adeleke_

2020-12-17 22:13 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done amazingly well so far. All previously required changes have been implemented. Everything seems to be working.
Two major issues are preventing me from approving your project. Let's look into it.__

**[ REQUIRED CHANGES ]**

- [ ] In the `All Users` page, there is a strange output printed below the users. Check the image below for details.

![001](https://user-images.githubusercontent.com/26856491/102549672-ce0e3900-40bc-11eb-9fce-31ceafd2dcca.png)

- [ ] Secondly, some of your test cases are failing. Check the image below to see the affected test cases.

![002](https://user-images.githubusercontent.com/26856491/102549826-10d01100-40bd-11eb-969c-9a7461f1b006.png)



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-12-17 22:13 UTC, teekaytech commented on app/views/users/_pending.html.erb
> +    <% end %>
Again, this is a block of logic inside your view. 
Kindly move this to a helper file.

2020-12-17 23:51 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2020-12-21 14:55 UTC, merged